language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="mirage-bootvar-xen"
  - DISTRO=alpine
  matrix:
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.08
